#Tue Aug 06 07:56:07 UTC 2024
micronaut:
  application:
    name:default

  server:
    port: ${SERVER_PORT:8080}


endpoints:
  prometheus:
    sensitive: false

  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true


